DROP TABLE APP.BOOKING;
CREATE TABLE APP.BOOKING
(
    idBooking INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    begin_of_booking TIMESTAMP,
    end_of_booking TIMESTAMP,
    Client_idClient INT,
    Room_idRoom INT,
    
    FOREIGN KEY (Client_idClient) REFERENCES CLIENT(idClient),
    FOREIGN KEY (Room_idRoom) REFERENCES ROOM(idRoom)
);

