DROP TABLE APP.OPERATION;
CREATE TABLE APP.OPERATION
(
    idOperation INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DBUser_idDBUser INT,
    operation VARCHAR(45),
    date TIMESTAMP,
    PRIMARY KEY (idOperation),
    FOREIGN KEY (DBUser_idDBUser) REFERENCES APP.DBUSER(idDBUser)
);