DROP TABLE APP.BOOKING;
CREATE TABLE APP.BOOKING
(
    idBooking INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    

    CONSTRAINT booking_primay_key PRIMARY KEY (idBooking),
    CONSTRAINT Booking_FKIndex1 FOREIGN KEY (Client_idClient) REFERENCES APP.CLIENT(idClient),
    CONSTRAINT Booking_FKIndex2 FREIGN KEY (Bill_idBill) REFERENCES APP.BILL(idBill)
);

