--DROP TABLE APP.LEGEND
CREATE TABLE APP.LEGEND
(
    idLegend INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    legend_name VARCHAR(45),
    color VARCHAR(45)
)
